name: C/C++ CI

on: [push]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Massage
      run: echo "Hello World from Deploy job"
    

 
